#!/usr/bin/env bash

# Colors taken from tokyonight theme
red="0xfff7768e"
blue="0xff7aa2f7"
transparent="0x00000000"

options=(
  active_color="$blue"
  inactive_color="$transparent"
  hidpi=on
  order=above
  style=round
  width=10.0
)

borders "${options[@]}"
