#!/usr/bin/env bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
FONT="SF Pro Display JP"
ICON_FONT="SF Pro"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar={
    position=top
    height=40
    color=0x00000000
  }

sketchybar --bar ${bar[@]}

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  label.font="$FONT:Bold:14.0"
  label.color=0xffffffff
  label.padding_left=4
  label.padding_right=10
  icon.font="$ICON_FONT:Bold:18.0"
  icon.color=0xffffffff
  icon.padding_left=10
  icon.padding_right=4
  popup.background.color=0x6a282a36
  popup.background.border_width=1
  popup.background.border_color=0x48ffffff
  popup.background.corner_radius=3
  popup.blur_radius=10
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.
add_item() {
  local name="$1"
  local position="$2"
  shift 2
  local args=("$name")
  while [[ $# -gt 0 ]]; do
    if [[ "$1" == --* ]]; then
      args+=("$1" "$name")
    else
      args+=("$1")
    fi
    shift
  done
  sketchybar --add item "$name" "$position" --set "${args[@]}"
}
add_bracket() {
  local name="$1"
  shift
  local config=(
    blur_radius=10
    background.height=32
    background.color=0x6a282a36
    background.corner_radius=8
    background.border_width=1
    background.border_color=0x48ffffff
  )
  sketchybar --add bracket "$name" "$@" --set "$name" "${config[@]}"
}
_SPACER_COUNT=0
add_spacer() {
  _SPACER_COUNT=$((_SPACER_COUNT + 1))
  local name="spacer.$_SPACER_COUNT"
  sketchybar --add item "$name" "$1" --set "$name" width=25
}

########## Events ##########

sketchybar --add event aerospace_workspace_change
sketchybar --add event date_boundary

########## Left Items ##########

# Apple Logo
add_item apple_logo left \
  icon='􀣺' \
  label.drawing=off \
  icon.padding_left=10 \
  icon.padding_right=11 \
  click_script="sketchybar -m --set \$NAME popup.drawing=toggle"
add_item preferences_button popup.apple_logo \
  icon='􀺽' \
  label="Preferences" \
  click_script="open -a 'System Preferences';
                sketchybar -m --set apple_logo popup.drawing=off"
add_item activity_button popup.apple_logo \
  icon='􀒓' \
  label="Activity Monitor" \
  click_script="open -a 'Activity Monitor';
               sketchybar -m --set apple_logo popup.drawing=off"
add_item lock_button popup.apple_logo \
  icon='􀒳' \
  label="Lock Screen" \
  click_script="pmset displaysleepnow;
                sketchybar -m --set apple_logo popup.drawing=off"
add_item sleep_button popup.apple_logo \
  icon='􀶠' \
  label="Sleep" \
  click_script="pmset sleepnow;
                sketchybar -m --set apple_logo popup.drawing=off"
add_item reload_button popup.apple_logo \
  icon='􀖋' \
  label="Reload SketchyBar" \
  click_script="sketchybar --reload"
add_bracket apple_logo_bracket apple_logo

# Spacer
add_spacer left

# Workspaces
add_item workspace.icon left \
  icon='􀏧' \
  icon.font.size=14 \
  icon.padding_right=5 \
  label.drawing=off
for sid in {1..9} 0; do
  add_item "workspace.$sid" left \
    icon.drawing=off \
    label="$sid" \
    label.font.size=18 \
    label.padding_right=10 \
    label.padding_left=10 \
    script="$PLUGIN_DIR/workspace.sh" \
    click_script="aerospace workspace $sid" \
    --subscribe aerospace_workspace_change
done
add_bracket workspace_bracket '/workspace\..*/'

# Spacer
add_spacer left

# Front App
add_item front_app left \
  icon='􀆊' \
  icon.font.size=14 \
  label.padding_left=10 \
  script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app_switched
add_bracket front_app_bracket front_app

########## Right Items ##########

# Time & Date
add_item time right \
  icon='􀐫' \
  script="$PLUGIN_DIR/time.sh" \
  update_freq=1 \
  label.width=80
add_item date right \
  icon='􀉉' \
  script="$PLUGIN_DIR/date.sh" \
  --subscribe system_woke date_boundary
add_bracket datetime_bracket date time

# Spacer
add_spacer right

# Battery
add_item battery right \
  script="$PLUGIN_DIR/battery.sh" \
  update_freq=5 \
  --subscribe power_source_change
add_bracket battery_bracket battery

# Spacer
add_spacer right

# Wi-Fi & Volume
add_item wifi right \
  script="$PLUGIN_DIR/wifi.sh" \
  --subscribe wifi_change
add_item volume right \
  script="$PLUGIN_DIR/volume.sh" \
  icon.width=36 \
  --subscribe volume_change
add_bracket wifi_volume_bracket volume wifi

# Spacer
add_spacer right

# Memory & CPU
add_item memory right \
  icon='􀫦' \
  script="$PLUGIN_DIR/memory.sh" \
  update_freq=5
add_item cpu right \
  icon='􀫥' \
  script="$PLUGIN_DIR/cpu.sh" \
  update_freq=5
add_bracket sysinfo_bracket memory cpu

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid="$(($i+1))"
#   space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]}"
#     icon.padding_left=7
#     icon.padding_right=7
#     background.color=0x40ffffff
#     background.corner_radius=5
#     background.height=25
#     label.drawing=off
#     script="$PLUGIN_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done
#
# ##### Adding Left Items #####
# # We add some regular items to the left side of the bar, where
# # only the properties deviating from the current defaults need to be set
#
# sketchybar --add item chevron left \
#            --set chevron icon= label.drawing=off \
#            --add item front_app left \
#            --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
#            --subscribe front_app front_app_switched
#
# ##### Adding Right Items #####
# # In the same way as the left items we can add items to the right side.
# # Additional position (e.g. center) are available, see:
# # https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar
#
# # Some items refresh on a fixed cycle, e.g. the clock runs its script once
# # every 10s. Other items respond to events they subscribe to, e.g. the
# # volume.sh script is only executed once an actual change in system audio
# # volume is registered. More info about the event system can be found here:
# # https://felixkratz.github.io/SketchyBar/config/events
#
# sketchybar --add item clock right \
#            --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
#            --add item volume right \
#            --set volume script="$PLUGIN_DIR/volume.sh" \
#            --subscribe volume volume_change \
#            --add item battery right \
#            --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
#            --subscribe battery system_woke power_source_change
#
# ##### Force all scripts to run the first time (never do this in a script) #####
# sketchybar --update
