local wezterm = require("wezterm")
local act = wezterm.action

return {
	keys = {
		{ key = "Tab", mods = "CTRL", action = act.ActivateTabRelative(1) },
		{ key = "Tab", mods = "SHIFT|CTRL", action = act.ActivateTabRelative(-1) },
		{ key = "Enter", mods = "SHIFT", action = act.SendString("\n") },
		{ key = "Enter", mods = "ALT", action = act.ToggleFullScreen },
		{ key = "Space", mods = "SUPER", action = act.QuickSelect },
		{ key = "+", mods = "SUPER", action = act.IncreaseFontSize },
		{ key = "-", mods = "SUPER", action = act.DecreaseFontSize },
		{ key = "-", mods = "LEADER", action = act.SplitVertical({ domain = "CurrentPaneDomain" }) },
		{ key = "0", mods = "SUPER", action = act.ResetFontSize },
		{ key = "1", mods = "SUPER", action = act.ActivateTab(0) },
		{ key = "2", mods = "SUPER", action = act.ActivateTab(1) },
		{ key = "3", mods = "SUPER", action = act.ActivateTab(2) },
		{ key = "4", mods = "SUPER", action = act.ActivateTab(3) },
		{ key = "5", mods = "SUPER", action = act.ActivateTab(4) },
		{ key = "6", mods = "SUPER", action = act.ActivateTab(5) },
		{ key = "7", mods = "SUPER", action = act.ActivateTab(6) },
		{ key = "8", mods = "SUPER", action = act.ActivateTab(7) },
		{ key = "9", mods = "SUPER", action = act.ActivateTab(-1) },
		{ key = "C", mods = "CTRL", action = act.CopyTo("Clipboard") },
		{ key = "H", mods = "CTRL", action = act.ActivatePaneDirection("Left") },
		{ key = "J", mods = "CTRL", action = act.ActivatePaneDirection("Down") },
		{ key = "K", mods = "CTRL", action = act.ActivatePaneDirection("Up") },
		{ key = "L", mods = "CTRL", action = act.ActivatePaneDirection("Right") },
		{ key = "P", mods = "CTRL", action = act.ActivateCommandPalette },
		{ key = "R", mods = "CTRL", action = act.ReloadConfiguration },
		{
			key = "U",
			mods = "CTRL",
			action = act.CharSelect({ copy_on_select = true, copy_to = "ClipboardAndPrimarySelection" }),
		},
		{
			key = "X",
			mods = "CTRL",
			action = act.Multiple({
				"ActivateCopyMode",
				{ CopyMode = "ClearPattern" },
				{ CopyMode = "ClearSelectionMode" },
				{ CopyMode = "MoveToViewportMiddle" },
			}),
		},
		{ key = "Z", mods = "CTRL", action = act.EmitEvent("user-defined-0") },
		{ key = "[", mods = "ALT", action = act.ScrollToPrompt(-1) },
		{ key = "]", mods = "ALT", action = act.ScrollToPrompt(1) },
		{
			key = "a",
			mods = "LEADER",
			action = act.QuickSelectArgs({
				action = { EmitEvent = "user-defined-1" },
				alphabet = "",
				label = "open\u{20}aws\u{20}console",
				patterns = { "\\barn:[\\w\\-]+:[\\w\\-]+:[\\w\\-]*:[0-9]*:[\\w\\-/:=.]+" },
			}),
		},
		{ key = "b", mods = "LEADER", action = act.EmitEvent("user-defined-3") },
		{ key = "c", mods = "SUPER", action = act.CopyTo("Clipboard") },
		{
			key = "f",
			mods = "SUPER",
			action = act.Multiple({
				{ Search = "CurrentSelectionOrEmptyString" },
				{ CopyMode = "ClearPattern" },
				{ CopyMode = "ClearSelectionMode" },
			}),
		},
		{ key = "l", mods = "SUPER", action = act.ShowDebugOverlay },
		{ key = "n", mods = "ALT|CTRL", action = act.ScrollByPage(0.5) },
		{ key = "n", mods = "SUPER", action = act.SpawnWindow },
		{ key = "p", mods = "ALT|CTRL", action = act.ScrollByPage(-0.5) },
		{ key = "q", mods = "SUPER", action = act.QuitApplication },
		{ key = "r", mods = "SUPER", action = act.ReloadConfiguration },
		{ key = "s", mods = "CTRL|SUPER", action = act.EmitEvent("user-defined-22") },
		{
			key = "s",
			mods = "LEADER",
			action = act.ActivateKeyTable({
				name = "setting_mode",
				one_shot = false,
				prevent_fallback = false,
				replace_current = false,
				until_unknown = false,
			}),
		},
		{ key = "t", mods = "SUPER", action = act.SpawnTab("CurrentPaneDomain") },
		{ key = "v", mods = "SUPER", action = act.PasteFrom("Clipboard") },
		{ key = "w", mods = "SUPER", action = act.CloseCurrentTab({ confirm = true }) },
		{ key = "w", mods = "LEADER", action = act.EmitEvent("user-defined-23") },
		{ key = "x", mods = "LEADER", action = act.CloseCurrentPane({ confirm = true }) },
		{ key = "z", mods = "LEADER", action = act.EmitEvent("user-defined-2") },
		{ key = "|", mods = "LEADER", action = act.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
		{ key = "\u{a5}", mods = "ALT", action = act.SendString("\\") },
		{ key = "PageUp", mods = "SHIFT", action = act.ScrollByPage(-1) },
		{ key = "PageDown", mods = "SHIFT", action = act.ScrollByPage(1) },
		{ key = "Copy", mods = "NONE", action = act.CopyTo("Clipboard") },
		{ key = "Paste", mods = "NONE", action = act.PasteFrom("Clipboard") },
	},

	key_tables = {
		copy_mode = {
			{ key = "Escape", mods = "NONE", action = act.Multiple({ "ScrollToBottom", { CopyMode = "Close" } }) },
			{ key = "$", mods = "NONE", action = act.CopyMode("MoveToEndOfLineContent") },
			{ key = ",", mods = "NONE", action = act.CopyMode("JumpReverse") },
			{ key = "/", mods = "NONE", action = act.Search("CurrentSelectionOrEmptyString") },
			{ key = "0", mods = "NONE", action = act.CopyMode("MoveToStartOfLine") },
			{ key = ";", mods = "NONE", action = act.CopyMode("JumpAgain") },
			{ key = "F", mods = "NONE", action = act.CopyMode({ JumpBackward = { prev_char = false } }) },
			{ key = "G", mods = "NONE", action = act.CopyMode("MoveToScrollbackBottom") },
			{ key = "H", mods = "NONE", action = act.CopyMode("MoveToViewportTop") },
			{ key = "L", mods = "NONE", action = act.CopyMode("MoveToViewportBottom") },
			{ key = "M", mods = "NONE", action = act.CopyMode("MoveToViewportMiddle") },
			{ key = "O", mods = "NONE", action = act.CopyMode("MoveToSelectionOtherEndHoriz") },
			{ key = "T", mods = "NONE", action = act.CopyMode({ JumpBackward = { prev_char = true } }) },
			{ key = "V", mods = "NONE", action = act.CopyMode({ SetSelectionMode = "Line" }) },
			{ key = "[", mods = "NONE", action = act.CopyMode({ MoveBackwardZoneOfType = "Input" }) },
			{ key = "[", mods = "ALT", action = act.ScrollToPrompt(-1) },
			{ key = "]", mods = "NONE", action = act.CopyMode({ MoveForwardZoneOfType = "Input" }) },
			{ key = "]", mods = "ALT", action = act.ScrollToPrompt(1) },
			{ key = "^", mods = "NONE", action = act.CopyMode("MoveToStartOfLineContent") },
			{ key = "b", mods = "NONE", action = act.CopyMode("MoveBackwardWord") },
			{ key = "b", mods = "CTRL", action = act.CopyMode("PageUp") },
			{ key = "c", mods = "CTRL", action = act.Multiple({ "ScrollToBottom", { CopyMode = "Close" } }) },
			{ key = "d", mods = "CTRL", action = act.CopyMode({ MoveByPage = 0.5 }) },
			{ key = "e", mods = "NONE", action = act.CopyMode("MoveForwardWordEnd") },
			{ key = "f", mods = "NONE", action = act.CopyMode({ JumpForward = { prev_char = false } }) },
			{ key = "f", mods = "CTRL", action = act.CopyMode("PageDown") },
			{ key = "g", mods = "NONE", action = act.CopyMode("MoveToScrollbackTop") },
			{ key = "h", mods = "NONE", action = act.CopyMode("MoveLeft") },
			{ key = "j", mods = "NONE", action = act.CopyMode("MoveDown") },
			{ key = "k", mods = "NONE", action = act.CopyMode("MoveUp") },
			{ key = "l", mods = "NONE", action = act.CopyMode("MoveRight") },
			{ key = "m", mods = "ALT", action = act.CopyMode("MoveToStartOfLineContent") },
			{ key = "n", mods = "CTRL", action = act.CopyMode("NextMatch") },
			{ key = "n", mods = "ALT|CTRL", action = act.CopyMode("PageDown") },
			{ key = "o", mods = "NONE", action = act.CopyMode("MoveToSelectionOtherEnd") },
			{ key = "p", mods = "CTRL", action = act.CopyMode("PriorMatch") },
			{ key = "p", mods = "ALT|CTRL", action = act.CopyMode("PageUp") },
			{ key = "q", mods = "NONE", action = act.Multiple({ "ScrollToBottom", { CopyMode = "Close" } }) },
			{ key = "t", mods = "NONE", action = act.CopyMode({ JumpForward = { prev_char = true } }) },
			{ key = "u", mods = "CTRL", action = act.CopyMode({ MoveByPage = -0.5 }) },
			{ key = "v", mods = "NONE", action = act.CopyMode({ SetSelectionMode = "Cell" }) },
			{ key = "v", mods = "CTRL", action = act.CopyMode({ SetSelectionMode = "Block" }) },
			{ key = "w", mods = "NONE", action = act.CopyMode("MoveForwardWord") },
			{ key = "y", mods = "NONE", action = act.Multiple({ { CopyTo = "ClipboardAndPrimarySelection" } }) },
			{ key = "z", mods = "NONE", action = act.CopyMode({ SetSelectionMode = "SemanticZone" }) },
		},

		search_mode = {
			{ key = "Escape", mods = "NONE", action = act.CopyMode("Close") },
			{ key = "X", mods = "CTRL", action = act.ActivateCopyMode },
			{ key = "n", mods = "CTRL", action = act.Multiple({ { CopyMode = "NextMatch" }, "ActivateCopyMode" }) },
			{ key = "p", mods = "CTRL", action = act.Multiple({ { CopyMode = "PriorMatch" }, "ActivateCopyMode" }) },
			{ key = "r", mods = "CTRL", action = act.CopyMode("CycleMatchType") },
			{ key = "u", mods = "CTRL", action = act.CopyMode("ClearPattern") },
		},

		setting_mode = {
			{ key = "Escape", mods = "NONE", action = act.PopKeyTable },
			{ key = "-", mods = "NONE", action = act.EmitEvent("decrease-opacity") },
			{ key = "0", mods = "NONE", action = act.EmitEvent("reset-opacity") },
			{
				key = "1",
				mods = "NONE",
				action = act.EmitEvent(" 》wezterm show-keys | grep AdjustPan 》wezterm show-keys | grep AdjustPaneeuser-defined-4"),
			},
			{ key = "1", mods = "CTRL", action = act.EmitEvent("user-defined-13") },
			{ key = "2", mods = "NONE", action = act.EmitEvent("user-defined-5") },
			{ key = "2", mods = "CTRL", action = act.EmitEvent("user-defined-14") },
			{ key = "3", mods = "NONE", action = act.EmitEvent("user-defined-6") },
			{ key = "3", mods = "CTRL", action = act.EmitEvent("user-defined-15") },
			{ key = "4", mods = "NONE", action = act.EmitEvent("user-defined-7") },
			{ key = "4", mods = "CTRL", action = act.EmitEvent("user-defined-16") },
			{ key = "5", mods = "NONE", action = act.EmitEvent("user-defined-8") },
			{ key = "5", mods = "CTRL", action = act.EmitEvent("user-defined-17") },
			{ key = "6", mods = "NONE", action = act.EmitEvent("user-defined-9") },
			{ key = "6", mods = "CTRL", action = act.EmitEvent("user-defined-18") },
			{ key = "7", mods = "NONE", action = act.EmitEvent("user-defined-10") },
			{ key = "7", mods = "CTRL", action = act.EmitEvent("user-defined-19") },
			{ key = "8", mods = "NONE", action = act.EmitEvent("user-defined-11") },
			{ key = "8", mods = "CTRL", action = act.EmitEvent("user-defined-20") },
			{ key = "9", mods = "NONE", action = act.EmitEvent("user-defined-12") },
			{ key = "9", mods = "CTRL", action = act.EmitEvent("user-defined-21") },
			{ key = ";", mods = "NONE", action = act.EmitEvent("increase-opacity") },
			{ key = "c", mods = "CTRL", action = act.PopKeyTable },
			{ key = "h", mods = "NONE", action = act.AdjustPaneSize({ "Left", 1 }) },
			{ key = "j", mods = "NONE", action = act.AdjustPaneSize({ "Down", 1 }) },
			{ key = "k", mods = "NONE", action = act.AdjustPaneSize({ "Up", 1 }) },
			{ key = "l", mods = "NONE", action = act.AdjustPaneSize({ "Right", 1 }) },
			{ key = "q", mods = "NONE", action = act.PopKeyTable },
		},

		workspace_mode = {
			{ key = "Escape", mods = "NONE", action = act.PopKeyTable },
			{
				key = "C",
				mods = "NONE",
				action = act.PromptInputLine({
					action = { EmitEvent = "user-defined-24" },
					description = "(wezterm)\u{20}Create\u{20}new\u{20}workspace:",
				}),
			},
		},
	},
}
