require("items.apple")
require("items.menus")
require("items.spaces")
require("items.front_app")
require("items.calendar")
require("items.widgets")
-- require("items.weather")
require("items.input")
require("items.media")
require("items.brew")
